name: empr
channels:
  - conda-forge
dependencies:
  - python=3.8
  - xarray
  - jupyterlab
  - nodejs
  - netCDF4
  - matplotlib
  - jupyter-panel-proxy
  - pyviz::holoviews
  - pyviz::panel
  - pyviz::bokeh
  - cmocean