name: empr
channels:
  - conda-forge
dependencies:
  - python=3.8
  - xarray
  - selenium
  - jupyterlab
  - nodejs
  - firefox
  - geckodriver
  - matplotlib
  - jupyter-panel-proxy
  - pyviz::holoviews
  - pyviz::panel
  - pyviz::bokeh
  - cmocean